"""baseline

Revision ID: 0001
Revises: 
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('local_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('visivel', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('lote_importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=300), nullable=False),
    sa.Column('arquivo_hash', sa.String(length=64), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=True),
    sa.Column('periodo_fim', sa.DateTime(), nullable=True),
    sa.Column('linhas_total', sa.Integer(), nullable=False),
    sa.Column('linhas_novas', sa.Integer(), nullable=False),
    sa.Column('linhas_ignoradas', sa.Integer(), nullable=False),
    sa.Column('linhas_pendentes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('confirmado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('sku_norm', sa.String(length=120), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('codigo_barras', sa.String(length=60), nullable=True),
    sa.Column('ml_item_id', sa.String(length=30), nullable=True),
    sa.Column('variacao', sa.String(length=200), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('imposto', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=120), nullable=True),
    sa.Column('foto', sa.String(length=400), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_ml_item_id'), ['ml_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_sku_norm'), ['sku_norm'], unique=True)
        batch_op.create_index(batch_op.f('ix_produto_tipo'), ['tipo'], unique=False)

    op.create_table('composicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('kit_id != componente_id', name='ck_composicao_nao_recursiva'),
    sa.CheckConstraint('quantidade >= 1', name='ck_composicao_qtd'),
    sa.ForeignKeyConstraint(['componente_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_id', 'componente_id', name='uq_composicao')
    )
    with op.batch_alter_table('composicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_composicao_componente_id'), ['componente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_composicao_kit_id'), ['kit_id'], unique=False)

    op.create_table('movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('saldo_apos', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('referencia_externa', sa.String(length=80), nullable=True),
    sa.Column('produto_vendido_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['local_estoque.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_importacao.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['produto_vendido_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimento_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_lote_id'), ['lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_referencia_externa'), ['referencia_externa'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_tipo'), ['tipo'], unique=False)
        batch_op.create_index('uq_movimento_idempotente', ['origem', 'referencia_externa', 'tipo', 'produto_id'], unique=True, sqlite_where=sa.text('referencia_externa IS NOT NULL'))

    op.create_table('saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['local_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'local_id', name='uq_saldo')
    )
    with op.batch_alter_table('saldo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saldo_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saldo_produto_id'), ['produto_id'], unique=False)

    op.create_table('vinculo_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=200), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vinculo_ml', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vinculo_ml_chave'), ['chave'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vinculo_ml', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vinculo_ml_chave'))

    op.drop_table('vinculo_ml')
    with op.batch_alter_table('saldo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saldo_produto_id'))
        batch_op.drop_index(batch_op.f('ix_saldo_local_id'))

    op.drop_table('saldo')
    with op.batch_alter_table('movimento', schema=None) as batch_op:
        batch_op.drop_index('uq_movimento_idempotente', sqlite_where=sa.text('referencia_externa IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_movimento_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimento_referencia_externa'))
        batch_op.drop_index(batch_op.f('ix_movimento_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimento_lote_id'))
        batch_op.drop_index(batch_op.f('ix_movimento_criado_em'))

    op.drop_table('movimento')
    with op.batch_alter_table('composicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_composicao_kit_id'))
        batch_op.drop_index(batch_op.f('ix_composicao_componente_id'))

    op.drop_table('composicao')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_tipo'))
        batch_op.drop_index(batch_op.f('ix_produto_sku_norm'))
        batch_op.drop_index(batch_op.f('ix_produto_ml_item_id'))
        batch_op.drop_index(batch_op.f('ix_produto_ativo'))

    op.drop_table('produto')
    op.drop_table('lote_importacao')
    op.drop_table('local_estoque')
    op.drop_table('config')
    # ### end Alembic commands ###
